org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

mod.id=coffeeauth
mod.name=CoffeeAuth
mod.version=1.0.0
mod.group=coffee.axle.sessionauth
mod.author=axlecoffee
mod.namespace=sessionauth
mod.display_name=CoffeeAuth
mod.description=Session ID login mod for Fabric
mod.discord=
mod.license=CC0-1.0
mod.github=axlecoffee/coffeeauth

client.user=
client.uuid=
client.modrinth_profiles_dir=

publish.modrinth=
publish.curseforge=
publish.maven_url=
publish.use_snapshot_maven=false

deps.minecraft=[VERSIONED]
deps.fapi=[VERSIONED]
deps.yarn_build=[VERSIONED]
deps.modmenu=[VERSIONED]
mod.mc_dep=[VERSIONED]
mod.mc_title=[VERSIONED]
mod.mc_targets=[VERSIONED]
